// Synced by scripts/sync_api.cjs.
export const nodeSchema = {
  Document: {
    style: {
      mode: "adapted",
      type: "PDFStyle | PDFStyle[]",
      required: false,
      note: "Typed PDF/SVG style dictionary or list; StyleSheet.create is represented by dictionaries.",
    },
    title: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    author: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    subject: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    creator: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    keywords: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    producer: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    language: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    creationDate: {
      mode: "adapted",
      type: "string",
      required: false,
      note: "ISO 8601 string validated and converted to Date.",
    },
    modificationDate: {
      mode: "adapted",
      type: "string",
      required: false,
      note: "ISO 8601 string validated and converted to Date.",
    },
    pdfVersion: {
      mode: "direct",
      type: '"1.3" | "1.4" | "1.5" | "1.6" | "1.7" | "1.7ext3"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    conformance: {
      mode: "direct",
      type: '"PDF/A-1" | "PDF/A-1b" | "PDF/A-2" | "PDF/A-2b" | "PDF/A-3" | "PDF/A-3b"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    pageMode: {
      mode: "direct",
      type: '"useNone" | "useOutlines" | "useThumbs" | "fullScreen" | "useOC" | "useAttachments"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    pageLayout: {
      mode: "direct",
      type: '"singlePage" | "oneColumn" | "twoColumnLeft" | "twoColumnRight" | "twoPageLeft" | "twoPageRight"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    ownerPassword: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    userPassword: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    permissions: {
      mode: "direct",
      type: "Permissions",
      required: false,
      note: "Same renderer property and semantics.",
    },
    onRender: {
      mode: "adapted",
      type: "FunctionProps",
      required: false,
      note: "Named registry function, original arguments followed by options and context.",
    },
  },
  Page: {
    wrap: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    layout: {
      mode: "adapted",
      type: "FunctionProps",
      required: false,
      note: "Named registry function, original arguments followed by options and context.",
    },
    experimentalPagination: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    debug: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    size: {
      mode: "direct",
      type: "string | (string | number)[] | { width: string | number; height?: string | number }",
      required: false,
      note: "Same renderer property and semantics.",
    },
    orientation: {
      mode: "direct",
      type: '"portrait" | "landscape"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    dpi: {
      mode: "direct",
      type: "number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    bookmark: {
      mode: "direct",
      type: "string | Bookmark",
      required: false,
      note: "Same renderer property and semantics.",
    },
    id: {
      mode: "adapted",
      type: "string | Record<string, any>",
      required: false,
      note: "Dash identity; string also defaults to PDF/SVG ID. pdfId overrides the PDF/SVG identity; object IDs never enter renderer.",
    },
    style: {
      mode: "adapted",
      type: "PDFStyle | PDFStyle[]",
      required: false,
      note: "Typed PDF/SVG style dictionary or list; StyleSheet.create is represented by dictionaries.",
    },
    fixed: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    break: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    minPresenceAhead: {
      mode: "direct",
      type: "number",
      required: false,
      note: "Same renderer property and semantics.",
    },
  },
  View: {
    id: {
      mode: "adapted",
      type: "string | Record<string, any>",
      required: false,
      note: "Dash identity; string also defaults to PDF/SVG ID. pdfId overrides the PDF/SVG identity; object IDs never enter renderer.",
    },
    wrap: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    debug: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    render: {
      mode: "adapted",
      type: "FunctionProps",
      required: false,
      note: "Named registry function, original arguments followed by options and context.",
    },
    style: {
      mode: "adapted",
      type: "PDFStyle | PDFStyle[]",
      required: false,
      note: "Typed PDF/SVG style dictionary or list; StyleSheet.create is represented by dictionaries.",
    },
    fixed: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    break: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    minPresenceAhead: {
      mode: "direct",
      type: "number",
      required: false,
      note: "Same renderer property and semantics.",
    },
  },
  Text: {
    id: {
      mode: "adapted",
      type: "string | Record<string, any>",
      required: false,
      note: "Dash identity; string also defaults to PDF/SVG ID. pdfId overrides the PDF/SVG identity; object IDs never enter renderer.",
    },
    wrap: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    debug: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    render: {
      mode: "adapted",
      type: "FunctionProps",
      required: false,
      note: "Named registry function, original arguments followed by options and context.",
    },
    hyphenationCallback: {
      mode: "adapted",
      type: "FunctionProps",
      required: false,
      note: "Named registry function, original arguments followed by options and context.",
    },
    hyphenationPenalty: {
      mode: "direct",
      type: "number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    orphans: {
      mode: "direct",
      type: "number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    widows: {
      mode: "direct",
      type: "number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    style: {
      mode: "adapted",
      type: "PDFStyle | PDFStyle[]",
      required: false,
      note: "Typed PDF/SVG style dictionary or list; StyleSheet.create is represented by dictionaries.",
    },
    fixed: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    break: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    minPresenceAhead: {
      mode: "direct",
      type: "number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    x: {
      mode: "direct",
      type: "string | number",
      required: true,
      note: "Same renderer property and semantics.",
    },
    y: {
      mode: "direct",
      type: "string | number",
      required: true,
      note: "Same renderer property and semantics.",
    },
    fill: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    color: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    stroke: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    transform: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeDasharray: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    opacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeWidth: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    fillOpacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    fillRule: {
      mode: "direct",
      type: '"nonzero" | "evenodd"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeOpacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    textAnchor: {
      mode: "direct",
      type: '"start" | "middle" | "end"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeLinecap: {
      mode: "direct",
      type: '"butt" | "round" | "square"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeLinejoin: {
      mode: "direct",
      type: '"butt" | "round" | "square" | "miter" | "bevel"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    visibility: {
      mode: "direct",
      type: '"visible" | "hidden" | "collapse"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    clipPath: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerStart: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerMid: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerEnd: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    dominantBaseline: {
      mode: "direct",
      type: '"middle" | "auto" | "central" | "hanging" | "mathematical" | "text-after-edge" | "text-before-edge"',
      required: false,
      note: "Same renderer property and semantics.",
    },
  },
  Image: {
    debug: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    cache: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    srcSet: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    sizes: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    id: {
      mode: "adapted",
      type: "string | Record<string, any>",
      required: false,
      note: "Dash identity; string also defaults to PDF/SVG ID. pdfId overrides the PDF/SVG identity; object IDs never enter renderer.",
    },
    style: {
      mode: "adapted",
      type: "PDFStyle | PDFStyle[]",
      required: false,
      note: "Typed PDF/SVG style dictionary or list; StyleSheet.create is represented by dictionaries.",
    },
    fixed: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    break: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    minPresenceAhead: {
      mode: "direct",
      type: "number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    src: {
      mode: "adapted",
      type: "ImageSource | FunctionProps",
      required: true,
      note: "URL/data URL, request dictionary, {data: base64, format}, byte list or named (possibly async) source function.",
    },
    source: {
      mode: "adapted",
      type: "ImageSource | FunctionProps",
      required: true,
      note: "URL/data URL, request dictionary, {data: base64, format}, byte list or named (possibly async) source function.",
    },
    x: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "SVG image coordinate from the browser implementation; omitted from upstream ImageProps.",
    },
    y: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "SVG image coordinate from the browser implementation; omitted from upstream ImageProps.",
    },
  },
  ImageBackground: {
    debug: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    cache: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    srcSet: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    sizes: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    imageStyle: {
      mode: "direct",
      type: "Record<string, any>",
      required: false,
      note: "Same renderer property and semantics.",
    },
    id: {
      mode: "adapted",
      type: "string | Record<string, any>",
      required: false,
      note: "Dash identity; string also defaults to PDF/SVG ID. pdfId overrides the PDF/SVG identity; object IDs never enter renderer.",
    },
    style: {
      mode: "adapted",
      type: "PDFStyle | PDFStyle[]",
      required: false,
      note: "Typed PDF/SVG style dictionary or list; StyleSheet.create is represented by dictionaries.",
    },
    fixed: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    break: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    minPresenceAhead: {
      mode: "direct",
      type: "number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    src: {
      mode: "adapted",
      type: "ImageSource | FunctionProps",
      required: true,
      note: "URL/data URL, request dictionary, {data: base64, format}, byte list or named (possibly async) source function.",
    },
    source: {
      mode: "adapted",
      type: "ImageSource | FunctionProps",
      required: true,
      note: "URL/data URL, request dictionary, {data: base64, format}, byte list or named (possibly async) source function.",
    },
  },
  Link: {
    wrap: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    debug: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    href: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    src: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    hitSlop: {
      mode: "direct",
      type: 'number | { "top"?: number; "bottom"?: number; "left"?: number; "right"?: number }',
      required: false,
      note: "Same renderer property and semantics.",
    },
    id: {
      mode: "adapted",
      type: "string | Record<string, any>",
      required: false,
      note: "Dash identity; string also defaults to PDF/SVG ID. pdfId overrides the PDF/SVG identity; object IDs never enter renderer.",
    },
    style: {
      mode: "adapted",
      type: "PDFStyle | PDFStyle[]",
      required: false,
      note: "Typed PDF/SVG style dictionary or list; StyleSheet.create is represented by dictionaries.",
    },
    fixed: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    break: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    minPresenceAhead: {
      mode: "direct",
      type: "number",
      required: false,
      note: "Same renderer property and semantics.",
    },
  },
  Note: {
    children: {
      mode: "direct",
      type: "string",
      required: true,
      note: "Same renderer property and semantics.",
    },
    id: {
      mode: "adapted",
      type: "string | Record<string, any>",
      required: false,
      note: "Dash identity; string also defaults to PDF/SVG ID. pdfId overrides the PDF/SVG identity; object IDs never enter renderer.",
    },
    style: {
      mode: "adapted",
      type: "PDFStyle | PDFStyle[]",
      required: false,
      note: "Typed PDF/SVG style dictionary or list; StyleSheet.create is represented by dictionaries.",
    },
    fixed: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    break: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    minPresenceAhead: {
      mode: "direct",
      type: "number",
      required: false,
      note: "Same renderer property and semantics.",
    },
  },
  Canvas: {
    debug: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    paint: {
      mode: "adapted",
      type: "FunctionProps",
      required: true,
      note: "Named registry function, original arguments followed by options and context.",
    },
    id: {
      mode: "adapted",
      type: "string | Record<string, any>",
      required: false,
      note: "Dash identity; string also defaults to PDF/SVG ID. pdfId overrides the PDF/SVG identity; object IDs never enter renderer.",
    },
    style: {
      mode: "adapted",
      type: "PDFStyle | PDFStyle[]",
      required: false,
      note: "Typed PDF/SVG style dictionary or list; StyleSheet.create is represented by dictionaries.",
    },
    fixed: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    break: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    minPresenceAhead: {
      mode: "direct",
      type: "number",
      required: false,
      note: "Same renderer property and semantics.",
    },
  },
  FieldSet: {
    name: {
      mode: "direct",
      type: "string",
      required: true,
      note: "Same renderer property and semantics.",
    },
    id: {
      mode: "adapted",
      type: "string | Record<string, any>",
      required: false,
      note: "Dash identity; string also defaults to PDF/SVG ID. pdfId overrides the PDF/SVG identity; object IDs never enter renderer.",
    },
    style: {
      mode: "adapted",
      type: "PDFStyle | PDFStyle[]",
      required: false,
      note: "Typed PDF/SVG style dictionary or list; StyleSheet.create is represented by dictionaries.",
    },
    fixed: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    break: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    minPresenceAhead: {
      mode: "direct",
      type: "number",
      required: false,
      note: "Same renderer property and semantics.",
    },
  },
  TextInput: {
    align: {
      mode: "direct",
      type: '"left" | "center" | "right"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    multiline: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    password: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    noSpell: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    format: {
      mode: "direct",
      type: '{ "type": "number" | "date" | "time" | "percent" | "zip" | "zipPlus4" | "phone" | "ssn"; "param"?: string; "nDec"?: number; "sepComma"?: boolean; "negStyle"?: "MinusBlack" | "Red" | "ParensBlack" | "ParensRed"; "currency"?: string; "currencyPrepend"?: boolean }',
      required: false,
      note: "Same renderer property and semantics.",
    },
    fontSize: {
      mode: "direct",
      type: "number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    maxLength: {
      mode: "direct",
      type: "number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    name: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    required: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    noExport: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    readOnly: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    value: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    defaultValue: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    id: {
      mode: "adapted",
      type: "string | Record<string, any>",
      required: false,
      note: "Dash identity; string also defaults to PDF/SVG ID. pdfId overrides the PDF/SVG identity; object IDs never enter renderer.",
    },
    style: {
      mode: "adapted",
      type: "PDFStyle | PDFStyle[]",
      required: false,
      note: "Typed PDF/SVG style dictionary or list; StyleSheet.create is represented by dictionaries.",
    },
    fixed: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    break: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    minPresenceAhead: {
      mode: "direct",
      type: "number",
      required: false,
      note: "Same renderer property and semantics.",
    },
  },
  Checkbox: {
    backgroundColor: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    borderColor: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    checked: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    onState: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    offState: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    xMark: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    name: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    required: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    noExport: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    readOnly: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    value: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    defaultValue: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    id: {
      mode: "adapted",
      type: "string | Record<string, any>",
      required: false,
      note: "Dash identity; string also defaults to PDF/SVG ID. pdfId overrides the PDF/SVG identity; object IDs never enter renderer.",
    },
    style: {
      mode: "adapted",
      type: "PDFStyle | PDFStyle[]",
      required: false,
      note: "Typed PDF/SVG style dictionary or list; StyleSheet.create is represented by dictionaries.",
    },
    fixed: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    break: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    minPresenceAhead: {
      mode: "direct",
      type: "number",
      required: false,
      note: "Same renderer property and semantics.",
    },
  },
  Select: {
    sort: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    edit: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    multiSelect: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    noSpell: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    select: {
      mode: "direct",
      type: "(string)[]",
      required: false,
      note: "Same renderer property and semantics.",
    },
    name: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    required: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    noExport: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    readOnly: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    value: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    defaultValue: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    id: {
      mode: "adapted",
      type: "string | Record<string, any>",
      required: false,
      note: "Dash identity; string also defaults to PDF/SVG ID. pdfId overrides the PDF/SVG identity; object IDs never enter renderer.",
    },
    style: {
      mode: "adapted",
      type: "PDFStyle | PDFStyle[]",
      required: false,
      note: "Typed PDF/SVG style dictionary or list; StyleSheet.create is represented by dictionaries.",
    },
    fixed: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    break: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    minPresenceAhead: {
      mode: "direct",
      type: "number",
      required: false,
      note: "Same renderer property and semantics.",
    },
  },
  List: {
    sort: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    edit: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    multiSelect: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    noSpell: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    select: {
      mode: "direct",
      type: "(string)[]",
      required: false,
      note: "Same renderer property and semantics.",
    },
    name: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    required: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    noExport: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    readOnly: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    value: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    defaultValue: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    id: {
      mode: "adapted",
      type: "string | Record<string, any>",
      required: false,
      note: "Dash identity; string also defaults to PDF/SVG ID. pdfId overrides the PDF/SVG identity; object IDs never enter renderer.",
    },
    style: {
      mode: "adapted",
      type: "PDFStyle | PDFStyle[]",
      required: false,
      note: "Typed PDF/SVG style dictionary or list; StyleSheet.create is represented by dictionaries.",
    },
    fixed: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    break: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    minPresenceAhead: {
      mode: "direct",
      type: "number",
      required: false,
      note: "Same renderer property and semantics.",
    },
  },
  Svg: {
    debug: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    width: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    height: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    viewBox: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    preserveAspectRatio: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    id: {
      mode: "adapted",
      type: "string | Record<string, any>",
      required: false,
      note: "Dash identity; string also defaults to PDF/SVG ID. pdfId overrides the PDF/SVG identity; object IDs never enter renderer.",
    },
    style: {
      mode: "adapted",
      type: "PDFStyle | PDFStyle[]",
      required: false,
      note: "Typed PDF/SVG style dictionary or list; StyleSheet.create is represented by dictionaries.",
    },
    fixed: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    break: {
      mode: "direct",
      type: "boolean",
      required: false,
      note: "Same renderer property and semantics.",
    },
    minPresenceAhead: {
      mode: "direct",
      type: "number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    fill: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    color: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    stroke: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    transform: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeDasharray: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    opacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeWidth: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    fillOpacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    fillRule: {
      mode: "direct",
      type: '"nonzero" | "evenodd"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeOpacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    textAnchor: {
      mode: "direct",
      type: '"start" | "middle" | "end"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeLinecap: {
      mode: "direct",
      type: '"butt" | "round" | "square"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeLinejoin: {
      mode: "direct",
      type: '"butt" | "round" | "square" | "miter" | "bevel"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    visibility: {
      mode: "direct",
      type: '"visible" | "hidden" | "collapse"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    clipPath: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerStart: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerMid: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerEnd: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    dominantBaseline: {
      mode: "direct",
      type: '"middle" | "auto" | "central" | "hanging" | "mathematical" | "text-after-edge" | "text-before-edge"',
      required: false,
      note: "Same renderer property and semantics.",
    },
  },
  Line: {
    style: {
      mode: "adapted",
      type: "PDFStyle | PDFStyle[]",
      required: false,
      note: "Typed PDF/SVG style dictionary or list; StyleSheet.create is represented by dictionaries.",
    },
    x1: {
      mode: "direct",
      type: "string | number",
      required: true,
      note: "Same renderer property and semantics.",
    },
    x2: {
      mode: "direct",
      type: "string | number",
      required: true,
      note: "Same renderer property and semantics.",
    },
    y1: {
      mode: "direct",
      type: "string | number",
      required: true,
      note: "Same renderer property and semantics.",
    },
    y2: {
      mode: "direct",
      type: "string | number",
      required: true,
      note: "Same renderer property and semantics.",
    },
    fill: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    color: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    stroke: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    transform: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeDasharray: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    opacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeWidth: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    fillOpacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    fillRule: {
      mode: "direct",
      type: '"nonzero" | "evenodd"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeOpacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    textAnchor: {
      mode: "direct",
      type: '"start" | "middle" | "end"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeLinecap: {
      mode: "direct",
      type: '"butt" | "round" | "square"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeLinejoin: {
      mode: "direct",
      type: '"butt" | "round" | "square" | "miter" | "bevel"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    visibility: {
      mode: "direct",
      type: '"visible" | "hidden" | "collapse"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    clipPath: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerStart: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerMid: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerEnd: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    dominantBaseline: {
      mode: "direct",
      type: '"middle" | "auto" | "central" | "hanging" | "mathematical" | "text-after-edge" | "text-before-edge"',
      required: false,
      note: "Same renderer property and semantics.",
    },
  },
  Polyline: {
    style: {
      mode: "adapted",
      type: "PDFStyle | PDFStyle[]",
      required: false,
      note: "Typed PDF/SVG style dictionary or list; StyleSheet.create is represented by dictionaries.",
    },
    points: {
      mode: "direct",
      type: "string",
      required: true,
      note: "Same renderer property and semantics.",
    },
    fill: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    color: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    stroke: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    transform: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeDasharray: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    opacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeWidth: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    fillOpacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    fillRule: {
      mode: "direct",
      type: '"nonzero" | "evenodd"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeOpacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    textAnchor: {
      mode: "direct",
      type: '"start" | "middle" | "end"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeLinecap: {
      mode: "direct",
      type: '"butt" | "round" | "square"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeLinejoin: {
      mode: "direct",
      type: '"butt" | "round" | "square" | "miter" | "bevel"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    visibility: {
      mode: "direct",
      type: '"visible" | "hidden" | "collapse"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    clipPath: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerStart: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerMid: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerEnd: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    dominantBaseline: {
      mode: "direct",
      type: '"middle" | "auto" | "central" | "hanging" | "mathematical" | "text-after-edge" | "text-before-edge"',
      required: false,
      note: "Same renderer property and semantics.",
    },
  },
  Polygon: {
    style: {
      mode: "adapted",
      type: "PDFStyle | PDFStyle[]",
      required: false,
      note: "Typed PDF/SVG style dictionary or list; StyleSheet.create is represented by dictionaries.",
    },
    points: {
      mode: "direct",
      type: "string",
      required: true,
      note: "Same renderer property and semantics.",
    },
    fill: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    color: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    stroke: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    transform: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeDasharray: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    opacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeWidth: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    fillOpacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    fillRule: {
      mode: "direct",
      type: '"nonzero" | "evenodd"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeOpacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    textAnchor: {
      mode: "direct",
      type: '"start" | "middle" | "end"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeLinecap: {
      mode: "direct",
      type: '"butt" | "round" | "square"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeLinejoin: {
      mode: "direct",
      type: '"butt" | "round" | "square" | "miter" | "bevel"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    visibility: {
      mode: "direct",
      type: '"visible" | "hidden" | "collapse"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    clipPath: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerStart: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerMid: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerEnd: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    dominantBaseline: {
      mode: "direct",
      type: '"middle" | "auto" | "central" | "hanging" | "mathematical" | "text-after-edge" | "text-before-edge"',
      required: false,
      note: "Same renderer property and semantics.",
    },
  },
  Path: {
    style: {
      mode: "adapted",
      type: "PDFStyle | PDFStyle[]",
      required: false,
      note: "Typed PDF/SVG style dictionary or list; StyleSheet.create is represented by dictionaries.",
    },
    d: {
      mode: "direct",
      type: "string",
      required: true,
      note: "Same renderer property and semantics.",
    },
    fill: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    color: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    stroke: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    transform: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeDasharray: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    opacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeWidth: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    fillOpacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    fillRule: {
      mode: "direct",
      type: '"nonzero" | "evenodd"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeOpacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    textAnchor: {
      mode: "direct",
      type: '"start" | "middle" | "end"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeLinecap: {
      mode: "direct",
      type: '"butt" | "round" | "square"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeLinejoin: {
      mode: "direct",
      type: '"butt" | "round" | "square" | "miter" | "bevel"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    visibility: {
      mode: "direct",
      type: '"visible" | "hidden" | "collapse"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    clipPath: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerStart: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerMid: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerEnd: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    dominantBaseline: {
      mode: "direct",
      type: '"middle" | "auto" | "central" | "hanging" | "mathematical" | "text-after-edge" | "text-before-edge"',
      required: false,
      note: "Same renderer property and semantics.",
    },
  },
  Rect: {
    style: {
      mode: "adapted",
      type: "PDFStyle | PDFStyle[]",
      required: false,
      note: "Typed PDF/SVG style dictionary or list; StyleSheet.create is represented by dictionaries.",
    },
    x: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    y: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    width: {
      mode: "direct",
      type: "string | number",
      required: true,
      note: "Same renderer property and semantics.",
    },
    height: {
      mode: "direct",
      type: "string | number",
      required: true,
      note: "Same renderer property and semantics.",
    },
    rx: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    ry: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    fill: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    color: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    stroke: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    transform: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeDasharray: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    opacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeWidth: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    fillOpacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    fillRule: {
      mode: "direct",
      type: '"nonzero" | "evenodd"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeOpacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    textAnchor: {
      mode: "direct",
      type: '"start" | "middle" | "end"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeLinecap: {
      mode: "direct",
      type: '"butt" | "round" | "square"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeLinejoin: {
      mode: "direct",
      type: '"butt" | "round" | "square" | "miter" | "bevel"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    visibility: {
      mode: "direct",
      type: '"visible" | "hidden" | "collapse"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    clipPath: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerStart: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerMid: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerEnd: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    dominantBaseline: {
      mode: "direct",
      type: '"middle" | "auto" | "central" | "hanging" | "mathematical" | "text-after-edge" | "text-before-edge"',
      required: false,
      note: "Same renderer property and semantics.",
    },
  },
  Circle: {
    style: {
      mode: "adapted",
      type: "PDFStyle | PDFStyle[]",
      required: false,
      note: "Typed PDF/SVG style dictionary or list; StyleSheet.create is represented by dictionaries.",
    },
    cx: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    cy: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    r: {
      mode: "direct",
      type: "string | number",
      required: true,
      note: "Same renderer property and semantics.",
    },
    fill: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    color: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    stroke: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    transform: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeDasharray: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    opacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeWidth: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    fillOpacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    fillRule: {
      mode: "direct",
      type: '"nonzero" | "evenodd"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeOpacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    textAnchor: {
      mode: "direct",
      type: '"start" | "middle" | "end"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeLinecap: {
      mode: "direct",
      type: '"butt" | "round" | "square"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeLinejoin: {
      mode: "direct",
      type: '"butt" | "round" | "square" | "miter" | "bevel"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    visibility: {
      mode: "direct",
      type: '"visible" | "hidden" | "collapse"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    clipPath: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerStart: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerMid: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerEnd: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    dominantBaseline: {
      mode: "direct",
      type: '"middle" | "auto" | "central" | "hanging" | "mathematical" | "text-after-edge" | "text-before-edge"',
      required: false,
      note: "Same renderer property and semantics.",
    },
  },
  Ellipse: {
    style: {
      mode: "adapted",
      type: "PDFStyle | PDFStyle[]",
      required: false,
      note: "Typed PDF/SVG style dictionary or list; StyleSheet.create is represented by dictionaries.",
    },
    cx: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    cy: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    rx: {
      mode: "direct",
      type: "string | number",
      required: true,
      note: "Same renderer property and semantics.",
    },
    ry: {
      mode: "direct",
      type: "string | number",
      required: true,
      note: "Same renderer property and semantics.",
    },
    fill: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    color: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    stroke: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    transform: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeDasharray: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    opacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeWidth: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    fillOpacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    fillRule: {
      mode: "direct",
      type: '"nonzero" | "evenodd"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeOpacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    textAnchor: {
      mode: "direct",
      type: '"start" | "middle" | "end"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeLinecap: {
      mode: "direct",
      type: '"butt" | "round" | "square"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeLinejoin: {
      mode: "direct",
      type: '"butt" | "round" | "square" | "miter" | "bevel"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    visibility: {
      mode: "direct",
      type: '"visible" | "hidden" | "collapse"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    clipPath: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerStart: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerMid: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerEnd: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    dominantBaseline: {
      mode: "direct",
      type: '"middle" | "auto" | "central" | "hanging" | "mathematical" | "text-after-edge" | "text-before-edge"',
      required: false,
      note: "Same renderer property and semantics.",
    },
  },
  Tspan: {
    x: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    y: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    fill: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    color: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    stroke: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    transform: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeDasharray: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    opacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeWidth: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    fillOpacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    fillRule: {
      mode: "direct",
      type: '"nonzero" | "evenodd"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeOpacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    textAnchor: {
      mode: "direct",
      type: '"start" | "middle" | "end"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeLinecap: {
      mode: "direct",
      type: '"butt" | "round" | "square"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeLinejoin: {
      mode: "direct",
      type: '"butt" | "round" | "square" | "miter" | "bevel"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    visibility: {
      mode: "direct",
      type: '"visible" | "hidden" | "collapse"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    clipPath: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerStart: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerMid: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerEnd: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    dominantBaseline: {
      mode: "direct",
      type: '"middle" | "auto" | "central" | "hanging" | "mathematical" | "text-after-edge" | "text-before-edge"',
      required: false,
      note: "Same renderer property and semantics.",
    },
  },
  G: {
    style: {
      mode: "adapted",
      type: "PDFStyle | PDFStyle[]",
      required: false,
      note: "Typed PDF/SVG style dictionary or list; StyleSheet.create is represented by dictionaries.",
    },
    fill: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    color: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    stroke: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    transform: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeDasharray: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    opacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeWidth: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    fillOpacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    fillRule: {
      mode: "direct",
      type: '"nonzero" | "evenodd"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeOpacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    textAnchor: {
      mode: "direct",
      type: '"start" | "middle" | "end"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeLinecap: {
      mode: "direct",
      type: '"butt" | "round" | "square"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    strokeLinejoin: {
      mode: "direct",
      type: '"butt" | "round" | "square" | "miter" | "bevel"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    visibility: {
      mode: "direct",
      type: '"visible" | "hidden" | "collapse"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    clipPath: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerStart: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerMid: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerEnd: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    dominantBaseline: {
      mode: "direct",
      type: '"middle" | "auto" | "central" | "hanging" | "mathematical" | "text-after-edge" | "text-before-edge"',
      required: false,
      note: "Same renderer property and semantics.",
    },
  },
  Stop: {
    offset: {
      mode: "direct",
      type: "string | number",
      required: true,
      note: "Same renderer property and semantics.",
    },
    stopColor: {
      mode: "direct",
      type: "string",
      required: true,
      note: "Same renderer property and semantics.",
    },
    stopOpacity: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
  },
  Defs: {},
  ClipPath: {
    id: {
      mode: "adapted",
      type: "string | Record<string, any>",
      required: false,
      note: "Dash identity; string also defaults to PDF/SVG ID. pdfId overrides the PDF/SVG identity; object IDs never enter renderer.",
    },
  },
  Marker: {
    id: {
      mode: "adapted",
      type: "string | Record<string, any>",
      required: true,
      note: "Dash identity; string also defaults to PDF/SVG ID. pdfId overrides the PDF/SVG identity; object IDs never enter renderer.",
    },
    viewBox: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    refX: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    refY: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerWidth: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerHeight: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    orient: {
      mode: "direct",
      type: 'number | "auto" | "auto-start-reverse"',
      required: false,
      note: "Same renderer property and semantics.",
    },
    markerUnits: {
      mode: "direct",
      type: '"strokeWidth" | "userSpaceOnUse"',
      required: false,
      note: "Same renderer property and semantics.",
    },
  },
  LinearGradient: {
    id: {
      mode: "adapted",
      type: "string | Record<string, any>",
      required: true,
      note: "Dash identity; string also defaults to PDF/SVG ID. pdfId overrides the PDF/SVG identity; object IDs never enter renderer.",
    },
    x1: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    x2: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    y1: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    y2: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    xlinkHref: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    gradientTransform: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    gradientUnits: {
      mode: "direct",
      type: '"userSpaceOnUse" | "objectBoundingBox"',
      required: false,
      note: "Same renderer property and semantics.",
    },
  },
  RadialGradient: {
    id: {
      mode: "adapted",
      type: "string | Record<string, any>",
      required: true,
      note: "Dash identity; string also defaults to PDF/SVG ID. pdfId overrides the PDF/SVG identity; object IDs never enter renderer.",
    },
    cx: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    cy: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    r: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    fx: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    fy: {
      mode: "direct",
      type: "string | number",
      required: false,
      note: "Same renderer property and semantics.",
    },
    xlinkHref: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    gradientTransform: {
      mode: "direct",
      type: "string",
      required: false,
      note: "Same renderer property and semantics.",
    },
    gradientUnits: {
      mode: "direct",
      type: '"userSpaceOnUse" | "objectBoundingBox"',
      required: false,
      note: "Same renderer property and semantics.",
    },
  },
} as const;
export const anchorFields = [
  "onClick",
  "hidden",
  "download",
  "hrefLang",
  "media",
  "ping",
  "target",
  "type",
  "referrerPolicy",
  "defaultChecked",
  "defaultValue",
  "suppressContentEditableWarning",
  "suppressHydrationWarning",
  "accessKey",
  "autoCapitalize",
  "autoFocus",
  "contentEditable",
  "contextMenu",
  "dir",
  "draggable",
  "enterKeyHint",
  "lang",
  "nonce",
  "slot",
  "spellCheck",
  "tabIndex",
  "title",
  "translate",
  "radioGroup",
  "role",
  "about",
  "content",
  "datatype",
  "inlist",
  "prefix",
  "property",
  "rel",
  "resource",
  "rev",
  "typeof",
  "vocab",
  "autoCorrect",
  "autoSave",
  "color",
  "itemProp",
  "itemScope",
  "itemType",
  "itemID",
  "itemRef",
  "results",
  "security",
  "unselectable",
  "popover",
  "popoverTargetAction",
  "popoverTarget",
  "inert",
  "inputMode",
  "is",
  "exportparts",
  "part",
  "aria-activedescendant",
  "aria-atomic",
  "aria-autocomplete",
  "aria-braillelabel",
  "aria-brailleroledescription",
  "aria-busy",
  "aria-checked",
  "aria-colcount",
  "aria-colindex",
  "aria-colindextext",
  "aria-colspan",
  "aria-controls",
  "aria-current",
  "aria-describedby",
  "aria-description",
  "aria-details",
  "aria-disabled",
  "aria-dropeffect",
  "aria-errormessage",
  "aria-expanded",
  "aria-flowto",
  "aria-grabbed",
  "aria-haspopup",
  "aria-hidden",
  "aria-invalid",
  "aria-keyshortcuts",
  "aria-label",
  "aria-labelledby",
  "aria-level",
  "aria-live",
  "aria-modal",
  "aria-multiline",
  "aria-multiselectable",
  "aria-orientation",
  "aria-owns",
  "aria-placeholder",
  "aria-posinset",
  "aria-pressed",
  "aria-readonly",
  "aria-relevant",
  "aria-required",
  "aria-roledescription",
  "aria-rowcount",
  "aria-rowindex",
  "aria-rowindextext",
  "aria-rowspan",
  "aria-selected",
  "aria-setsize",
  "aria-sort",
  "aria-valuemax",
  "aria-valuemin",
  "aria-valuenow",
  "aria-valuetext",
  "onCopy",
  "onCopyCapture",
  "onCut",
  "onCutCapture",
  "onPaste",
  "onPasteCapture",
  "onCompositionEnd",
  "onCompositionEndCapture",
  "onCompositionStart",
  "onCompositionStartCapture",
  "onCompositionUpdate",
  "onCompositionUpdateCapture",
  "onFocus",
  "onFocusCapture",
  "onBlur",
  "onBlurCapture",
  "onChange",
  "onChangeCapture",
  "onBeforeInput",
  "onBeforeInputCapture",
  "onInput",
  "onInputCapture",
  "onReset",
  "onResetCapture",
  "onSubmit",
  "onSubmitCapture",
  "onInvalid",
  "onInvalidCapture",
  "onLoad",
  "onLoadCapture",
  "onError",
  "onErrorCapture",
  "onKeyDown",
  "onKeyDownCapture",
  "onKeyPress",
  "onKeyPressCapture",
  "onKeyUp",
  "onKeyUpCapture",
  "onAbort",
  "onAbortCapture",
  "onCanPlay",
  "onCanPlayCapture",
  "onCanPlayThrough",
  "onCanPlayThroughCapture",
  "onDurationChange",
  "onDurationChangeCapture",
  "onEmptied",
  "onEmptiedCapture",
  "onEncrypted",
  "onEncryptedCapture",
  "onEnded",
  "onEndedCapture",
  "onLoadedData",
  "onLoadedDataCapture",
  "onLoadedMetadata",
  "onLoadedMetadataCapture",
  "onLoadStart",
  "onLoadStartCapture",
  "onPause",
  "onPauseCapture",
  "onPlay",
  "onPlayCapture",
  "onPlaying",
  "onPlayingCapture",
  "onProgress",
  "onProgressCapture",
  "onRateChange",
  "onRateChangeCapture",
  "onSeeked",
  "onSeekedCapture",
  "onSeeking",
  "onSeekingCapture",
  "onStalled",
  "onStalledCapture",
  "onSuspend",
  "onSuspendCapture",
  "onTimeUpdate",
  "onTimeUpdateCapture",
  "onVolumeChange",
  "onVolumeChangeCapture",
  "onWaiting",
  "onWaitingCapture",
  "onAuxClick",
  "onAuxClickCapture",
  "onClickCapture",
  "onContextMenu",
  "onContextMenuCapture",
  "onDoubleClick",
  "onDoubleClickCapture",
  "onDrag",
  "onDragCapture",
  "onDragEnd",
  "onDragEndCapture",
  "onDragEnter",
  "onDragEnterCapture",
  "onDragExit",
  "onDragExitCapture",
  "onDragLeave",
  "onDragLeaveCapture",
  "onDragOver",
  "onDragOverCapture",
  "onDragStart",
  "onDragStartCapture",
  "onDrop",
  "onDropCapture",
  "onMouseDown",
  "onMouseDownCapture",
  "onMouseEnter",
  "onMouseLeave",
  "onMouseMove",
  "onMouseMoveCapture",
  "onMouseOut",
  "onMouseOutCapture",
  "onMouseOver",
  "onMouseOverCapture",
  "onMouseUp",
  "onMouseUpCapture",
  "onSelect",
  "onSelectCapture",
  "onTouchCancel",
  "onTouchCancelCapture",
  "onTouchEnd",
  "onTouchEndCapture",
  "onTouchMove",
  "onTouchMoveCapture",
  "onTouchStart",
  "onTouchStartCapture",
  "onPointerDown",
  "onPointerDownCapture",
  "onPointerMove",
  "onPointerMoveCapture",
  "onPointerUp",
  "onPointerUpCapture",
  "onPointerCancel",
  "onPointerCancelCapture",
  "onPointerEnter",
  "onPointerLeave",
  "onPointerOver",
  "onPointerOverCapture",
  "onPointerOut",
  "onPointerOutCapture",
  "onGotPointerCapture",
  "onGotPointerCaptureCapture",
  "onLostPointerCapture",
  "onLostPointerCaptureCapture",
  "onScroll",
  "onScrollCapture",
  "onScrollEnd",
  "onScrollEndCapture",
  "onWheel",
  "onWheelCapture",
  "onAnimationStart",
  "onAnimationStartCapture",
  "onAnimationEnd",
  "onAnimationEndCapture",
  "onAnimationIteration",
  "onAnimationIterationCapture",
  "onToggle",
  "onBeforeToggle",
  "onTransitionCancel",
  "onTransitionCancelCapture",
  "onTransitionEnd",
  "onTransitionEndCapture",
  "onTransitionRun",
  "onTransitionRunCapture",
  "onTransitionStart",
  "onTransitionStartCapture",
  "width",
  "height",
  "showToolbar",
  "render",
  "previewMode",
  "pageNumber",
  "numPages",
  "frameId",
  "showDownload",
  "downloadLabel",
  "fonts",
  "emojiSource",
  "hyphenationCallback",
  "fontAction",
  "fontDescriptors",
  "autoGenerate",
  "n_generate",
  "n_render",
  "n_clicks",
  "loading",
  "error",
  "url",
  "size",
  "returnBase64",
  "data",
  "rendererVersion",
  "fontFamilies",
  "fontInfo",
] as const;
